In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
##To convert one-D to 2-D

In [4]:
newarr=arr.reshape(4,3)  # slice number and element count
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
check=arr.reshape(4,4)  # compilation error

ValueError: cannot reshape array of size 12 into shape (4,4)

In [6]:
newarr3D=arr.reshape(2,3,2)    # 2 array contains 3 array each of 2 elements
print(newarr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
arr2=np.array([1,2,3,4,5,6,7,8])
narr=arr2.reshape(2,2,2)
print(narr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
narr=arr2.reshape(2,2,-1)
print(narr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
