In [3]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [5]:
for x in arr:
    for j in x:
        print(j)

1
2
3
4
5
6


In [11]:
#we have 3-D array we just need one element and it's index

arrSearch=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a=0
b=0
c=0
for i in arrSearch:
    a=a+1
    for j in i:
        b=b+1
        for k in j:
            c=c+1
            print("%d is present at %dth element of %d array of %d array"%(k,a,b,c))

1 is present at 1th element of 1 array of 1 array
2 is present at 1th element of 1 array of 2 array
3 is present at 1th element of 1 array of 3 array
4 is present at 1th element of 2 array of 4 array
5 is present at 1th element of 2 array of 5 array
6 is present at 1th element of 2 array of 6 array
7 is present at 2th element of 3 array of 7 array
8 is present at 2th element of 3 array of 8 array
9 is present at 2th element of 3 array of 9 array
10 is present at 2th element of 4 array of 10 array
11 is present at 2th element of 4 array of 11 array
12 is present at 2th element of 4 array of 12 array


In [6]:
#3-D array with index for each element

In [7]:
for x in np.nditer(arr):   # converts all elements in 1-D array and remove other square brackets
    print(x)

1
2
3
4
5
6


In [8]:
## CONCATENATION

In [11]:
arr1=np.array([[1,2,3],[4,5,6]])

In [10]:
arr2=np.array([[7,8,9],[10,11,12]])

In [16]:
arr = np.concatenate((arr1,arr2),axis=1) # replace concatenate with stack
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [17]:
arr1=np.array([1,2,3]) # Heap Stack 
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2)) # Replace h with v for vertical stacking
print(arr)

[1 2 3 4 5 6]


In [18]:
arr = np.stack((arr1,arr2),axis=1) # replace concatenate with stack
print(arr)

[[1 4]
 [2 5]
 [3 6]]
